from .crawler import Crawler
from .boxnovel import BoxNovelCrawler
from .idqidian import IdqidianCrawler
from .lnindo import LnindoCrawler
from .lnmtl import LNMTLCrawler
from .novelplanet import NovelPlanetCrawler
from .readln import ReadLightNovelCrawler
from .webnovel import WebnovelCrawler
from .wuxia import WuxiaWorldCrawler
from .wuxiac import WuxiaCoCrawler
from .wuxiaonline import WuxiaOnlineCrawler
